export const RADIO_CHANNELS = [
  { id: 'lofi-hiphop', label: 'Lofi Hip Hop Radio', videoId: 'X4VbdwhkE10' },
  { id: 'synthwave', label: 'Synthwave Radio', videoId: '4xDzrJKXOOY' },
  { id: 'sleep-lofi', label: 'Sleep Lofi Radio', videoId: 'VAlMDl00mYY' },
  { id: 'sleep-ambient', label: 'Sleep Ambient Music', videoId: 'xORCbIptqcc' },
  { id: 'synth-ambient', label: 'Synth Ambient Radio', videoId: 'GSfT7H87zq4' },
  { id: 'jazz-lofi', label: 'Jazz Lofi Radio', videoId: 'E2vONfzoyRI' },
  { id: 'asian-lofi', label: 'Asian Lofi Radio', videoId: '1Tl2FtV06qo' },
  { id: 'sad-lofi', label: 'Sad Lofi Radio', videoId: 'CwPCy1GLS38' },
  { id: 'bossa-lofi', label: 'Bossa Lofi Radio', videoId: '56llPN9tS88' },
  { id: 'sleep-hiphop', label: 'Lofi Hip Hop to Sleep', videoId: 'JD-kMIpDfnY' },
  { id: 'relaxing-piano', label: 'Relaxing Piano Radio', videoId: 'N0snMcR6aaA' },
  { id: 'relaxing-jazz', label: 'Relaxing Jazz Music', videoId: 'A8jDx9TLMQc' },
  { id: 'study-with-me', label: 'Study with Me Pomodoro', videoId: 'qGohtGC5Rtk' },
  { id: 'christmas-lofi', label: 'Christmas Lofi Music', videoId: 'XSXEaikz0Bc' },
  { id: 'halloween-lofi', label: 'Halloween Lofi Radio', videoId: '3GQY80jyysQ' },
  { id: 'fireplace-ambience', label: 'Fireplace Ambience', videoId: 'q_4KI-ChIIs' },
  { id: 'chill-guitar', label: 'Chill Guitar Radio', videoId: 'E_XmwjgRLz8' },
  { id: 'medieval-lofi', label: 'Medieval Lofi Radio', videoId: 'IxPANmjPaek' },
  { id: 'gentle-rain', label: 'Gentle Rain Ambience', videoId: '-OekvEFm1lo' },
  { id: 'dark-ambient', label: 'Dark Ambient Music', videoId: 'S_MOd40zlYU' },
];
